resolver: lts-11.2

packages:
- .

extra-deps:
- pretty-tree-0.1.0.0
- git: https://github.com/hephaestus-ng/hephaestus-fm.git
  commit: HEAD
- git: https://github.com/hephaestus-ng/hephaestus-spl.git
  commit: HEAD
- git: https://github.com/hephaestus-ng/hephaestus-assets.git
  commit: HEAD
