iris => [define("irisbase"), select("iris")]
mail => [select("mail"), select("send"), select("receive")]
persistence => [select("persistence"), select("SQL")]
search => [select("search"), select("simple")]
And(search, advanced) => [select("advanced")]
contacts => [select("contacts")]
