iris => [define("iris-base"), select("iris")]
And(search, And(simple, Not(advanced)) => [select("search"), select("advanced")]
And(search, And(advanced, Not(simple)) => [select("search"), select("advanced")]
mail => select("mail")
send => select("send")
receive => select("receive")
persistence => [select("persistence"), select("SQL")]
And(persistence, NoSQL) => [select("NoSQL")]
contacts => [select("contacts")]
